export const budgetCategories = [
  { id: 1, name: 'Food and beverages', icon: '🍔' },
  { id: 2, name: 'Transportation', icon: '🚗' },
  { id: 3, name: 'Education', icon: '🎓' },
  { id: 4, name: 'Healthcare', icon: '🏥' },
  { id: 5, name: 'Entertainment', icon: '🎬' },
  { id: 6, name: 'Shopping', icon: '🛍️' },
  { id: 7, name: 'Housing', icon: '🏠' },
  { id: 8, name: 'Utilities', icon: '💡' },
  { id: 9, name: 'Insurance', icon: '🛡️' },
  { id: 10, name: 'Savings', icon: '💰' },
  { id: 11, name: 'Personal Care', icon: '💄' },
  { id: 12, name: 'Clothing', icon: '👔' },
  { id: 13, name: 'Gifts', icon: '🎁' },
  { id: 14, name: 'Travel', icon: '✈️' },
  { id: 15, name: 'Subscriptions', icon: '📱' },
];